# Generated by Django 4.1.7 on 2023-07-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
    ]
