# Generated by Django 4.1.7 on 2023-07-06 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('venta', '0002_remove_venta_marca_remove_venta_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.modelo'),
            preserve_default=False,
        ),
    ]
