# Generated by Django 4.1.7 on 2023-08-03 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0001_initial"),
        ("stock", "0002_ingresosuministro"),
        ("venta", "0003_venta_modelo"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="marca_producto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="categorias.marca",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stock.stocktienda"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="stocktienda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="categorias.producto"
            ),
        ),
    ]
